"""Export a case as a Markdown incident report."""
from __future__ import annotations

import time


def _cell(text) -> str:
    return str(text).replace("|", "\\|").replace("\n", " ")


def to_markdown(result: dict) -> str:
    r = result["report"]
    when = time.strftime("%Y-%m-%d %H:%M UTC", time.gmtime(result["created"])) if result.get("created") else "n/a"
    out = [f"# Incident report: {result.get('title', 'Alert')}", "",
           f"- **Alert:** {result.get('alert_id')}  ",
           f"- **Case:** {result.get('case_id', 'unsaved')}  ",
           f"- **Generated:** {when}  ",
           f"- **Risk:** {r['risk_score']}/100 ({r['severity']}), {r['verdict']}  ",
           f"- **Planner:** {result['engine']['llm']}", "",
           "## Summary", "", r["summary"], "", "## Why this score", "",
           "| Signal | Weight | Value |", "|---|---|---|"]
    out += [f"| {_cell(c['name'])} | {c['weight']} | {c['value']} |" for c in r["risk_components"]]
    hit = [k for k in r.get("kill_chain", []) if k["hit"]]
    out += ["", "## Kill-chain coverage", "",
            ", ".join(f"{k['tactic']} ({', '.join(k['techniques'])})" for k in hit) or "No tactic matched with confidence.", "",
            "## MITRE ATT&CK", ""]
    out += [f"- `{m['id']}` {m['name']} ({m['tactic']})" for m in r["mitre"]] or ["- none"]
    out += ["", "## Indicators matched in threat intelligence", ""]
    out += [f"- {h['type']} `{h['value']}`: {h['tag']} (confidence {h['confidence']})" for h in r["indicator_hits"]] or ["- none"]
    if r.get("similar_cases"):
        out += ["", "## Similar past cases", ""]
        out += [f"- Case #{c['case_id']} {c['title']} ({c['severity']}, similarity {c['similarity']})" for c in r["similar_cases"]]
    out += ["", "## Proposed response", ""]
    for a in r["recommendations"]:
        box = "x" if a["status"] == "approved" else " "
        note = f" *{a['status']}{' by ' + a['decided_by'] if a.get('decided_by') else ''}*"
        out.append(f"- [{box}] {a['action']} ({a['source']}){note}")
    out += ["", "## Evidence trail", "", "| Step | Tool | Result | ms |", "|---|---|---|---|"]
    out += [f"| {s['n']} | `{s['tool']}` | {_cell(s['observation'].get('summary', ''))} | {s['ms']} |" for s in result["steps"]]
    out += ["", "## Sources", ""] + [f"- {c['id']}: {c['title']} ({c['source']})" for c in r["citations"]]
    out += ["", "_Generated by AegisNexus. Proposed actions are recommendations and were not executed automatically._", ""]
    return "\n".join(out)
